### ISSUE TITLE
decommission the puppet actor

### ISSUE THREAD

**Issue by alanshaw** [filecoin-project/test-vectors#101]
Following up from https://github.com/filecoin-project/test-vectors/pull/100#pullrequestreview-480825971:

- [x] make the chaos actor `t98` (all vectors will be affected). https://github.com/filecoin-project/test-vectors/pull/104
- [x] PR to decommission the puppet actor from the driver (Lotus side). https://github.com/filecoin-project/lotus/pull/3490 https://github.com/filecoin-project/lotus/pull/3521

**Comment by willscott** [comment]
is there a reason we prefer chaos at 98 rather than 97? or just to make it clear that it replaces puppet?

**Comment by raulk** [comment]
Yeah, to replace the puppet actor and not leave any gaps in the address space.

**Comment by raulk** [comment]
@alanshaw I'll leave the satisfaction to you to close out this issue when https://github.com/filecoin-project/lotus/pull/3521 is merged ;-)
