### ISSUE TITLE
Test behaviour of DeleteActor and beneficiary

### ISSUE THREAD

**Issue by anorth** [filecoin-project/test-vectors#14]
Test the behaviour as documented on the runtime DeleteActor method, including payment of residual balance to the beneficiary, and failure if the beneficiary is invalid.

This can use the payment channel actor, which deletes after settlement, or by extending the chaos actor.

**Comment by alanshaw** [comment]
@anorth I was wondering what would happen if a system actor got deleted - presumably that would be bad news? I was thinking about using the beneficiary functionality to grab all the funds from the burnt funds actor or the reward actor. I saw that in lotus there's [no explicit guard against it](https://github.com/filecoin-project/lotus/blob/932ab61c2df0c0d4a6cf8628f0c0db267f2cae2a/chain/vm/runtime.go#L254-L275) but AFAIK an actor can only delete itself so this would be impossible.

**Comment by anorth** [comment]
Since an actor can only delete itself, I don't think we need to worry about the system actor being deleted: it doesn't have any code at all. Similarly for the other actors you mention. Being delete-able is an explicit opt-in behaviour.
