### ISSUE TITLE
Test that CreateActor aborts if provided an address that already exists

### ISSUE THREAD

**Issue by anorth** [filecoin-project/test-vectors#17]

**Comment by raulk** [comment]
@nonsense This should be pretty trivial to test. Let's add it to the `actor_creation` suite. In fact, there's a whole series of failure test cases missing there.

@anorth have you done any thinking on other failure cases in actor creation?

* actor creation fails and gas is deducted when providing a wrong actor code CID.
* actor creation fails and gas is deducted when passing in bad arguments to actor constructor via init actor.

**Comment by raulk** [comment]
https://github.com/filecoin-project/test-vectors/issues/18
https://github.com/filecoin-project/test-vectors/issues/19
https://github.com/filecoin-project/test-vectors/issues/20

**Comment by nonsense** [comment]
I am not sure how to create a `test vector` that can be run on multiple impl. for such a scenario.

There are a few blockers that I don't know how to pass:
1. The AccountActor Constructor has the following guard:
```
	// Account actors are created implicitly by sending a message to a pubkey-style address.
	// This constructor is not invoked by the InitActor, but by the system.
	rt.ValidateImmediateCallerIs(builtin.SystemActorAddr)
```

2. The InitActor Exec has the following guard:
```
	if !canExec(callerCodeCID, params.CodeCID) {
		rt.Abortf(exitcode.ErrForbidden, "caller type %v cannot exec actor type %v", callerCodeCID, params.CodeCID)
	}
```
where `canExec` is running:
```
func canExec(callerCodeID cid.Cid, execCodeID cid.Cid) bool {
	switch execCodeID {
	case builtin.StorageMinerActorCodeID:
		if callerCodeID == builtin.StoragePowerActorCodeID {
			return true
		}
		return false
	case builtin.PaymentChannelActorCodeID, builtin.MultisigActorCodeID:
		return true
	default:
		return false
	}
}
```

I am not sure how we can generate a message that could hit the code path of `CreateActor` - this doesn't seem to fit the `message schema` test vectors we currently have. Any suggestions?

**Comment by nonsense** [comment]
Now that the chaos actor exists, I know what to do, will report back.

**Comment by anorth** [comment]
Expect `SysErrorIllegalArgument`

**Comment by nonsense** [comment]
> Expect SysErrorIllegalArgument

Thanks @anorth ! I am indeed still struggling to confirm when an error is thrown that it is the correct error thrown from the place we expect, but I will get the hang of it.
