### ISSUE TITLE
Test that actor creation fails and gas is deducted when passing in unparseable constructor params via init actor

### ISSUE THREAD

**Issue by raulk** [filecoin-project/test-vectors#20]
Failure case in `actor_creation` suite.

1. Use `msg := v.Messages.Sugar().CreatePaychActor()` to stage a good paych construction message. Do not apply it.
2. Directly mangle the parameters to form an invalid CBOR payload by prepending a bunch of zero bytes to `msg.Message.Params`.
3. `CommitApplies()` and expect a failure.

**Comment by anorth** [comment]
LMK what exit code you get. It should be `ErrSerialization`, but there could well be confusion here.

**Comment by anorth** [comment]
Note changes happening in https://github.com/filecoin-project/specs-actors/pull/974

**Comment by nonsense** [comment]
It appears that we are getting `SysErrSenderInvalid` exitcode. Here is the code for the test: https://github.com/filecoin-project/test-vectors/pull/41/files#diff-125dd23b15db99e7b1e530100630fc62R42

**Comment by raulk** [comment]
Going to close this here, because we've captured the current behaviour (`SysErrSenderInvalid`) into an `incorrect` test vector in #41. Fix/discussion continues in https://github.com/filecoin-project/lotus/pull/3267.
