### ISSUE TITLE
Test caller validation requirements

### ISSUE THREAD

**Issue by anorth** [filecoin-project/test-vectors#31]
Check that:
- [x] a method must invoke at least one caller validation method, or abort
- [x] ValidateImmediateCallerIs() and ValidateImmediateCallerType() each abort if given no arguments
- [x] validating twice aborts the message

**Comment by raulk** [comment]
> a method must invoke at least one caller validation method, or abort

Can we test this by deploying an custom actor with a method that runs and returns `exitcode.Ok` without validating the caller?

> ValidateImmediateCallerIs() and ValidateImmediateCallerType() each abort if given no arguments

Ack.

---

I could think of a third scenario: test that validating twice aborts the message:

https://github.com/filecoin-project/lotus/blob/fe2da35a45807576672b3376224de2345f594575/chain/vm/runtime.go#L287

**Comment by anorth** [comment]
The runtime documentation doesn't state that validating twice should abort - that looks like an implementation improvisation. It's a good test case, because we should define the behaviour. Requiring exactly one call is marginally more complex, but probably makes sense.

**Comment by raulk** [comment]
Fixed in #39.
