### ISSUE TITLE
Test Runtime#ResolveAddress

### ISSUE THREAD

**Issue by anorth** [filecoin-project/test-vectors#47]
- If the address is an ID address, it should be returned directly, _even if no such actor exists_
- If the {pubkey|actor} address is not in the InitActor's table, return `(Undef, false)`
- If the {pubkey|actor} address is in the InitActor's table, the corresponding ID address should be returned

**Comment by willscott** [comment]
It'll be hard to test all of these edge cases at the message level that test vectors operate at, as i understand it. there's no way to directly call the `ResolveAddress` method of the init actor, so instead it'll be implicitly confirming that messages to different forms of the destination address work or not.

**Comment by raulk** [comment]
@willscott there was an ambiguity in the issue title. I changed it to reflect this is talking about `Runtime#ResolveAddress` (which transitively queries `InitActor` state).
