### ISSUE TITLE
[spike] full coverage of all actor methods

### ISSUE THREAD

**Issue by frrist** [filecoin-project/test-vectors#58]
Explore calling each actor and their corresponding methods. Can help avoid situations like: https://github.com/filecoin-project/go-filecoin/pull/4134

cc @icorderi

**Comment by raulk** [comment]
@anorth I suspect we will need to tackle this eventually to create test vectors for other implementations that cover the entire spectrum of actors, but not a priority for Lotus' coverage right now. Agree?

**Comment by anorth** [comment]
I agree, I don't think this should be a goal for test vectors in the near or even medium term. For now, other implementations should validate their actor implementations by replicating or expanding on their unit tests.
