### ISSUE TITLE
Remove reward state initialisation

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/test-vectors#59]
Once[ this issue](https://github.com/filecoin-project/specs-actors/issues/374) is fixed, we can remove the hacky thing in test.go that creates the reward state with an initial per reward message of 1e17.

**Comment by raulk** [comment]
@anorth we actually ended up migrating this "artifact" to our generators:

https://github.com/filecoin-project/test-vectors/blob/142e3c3584f4b00129b009d48cf39deda4c2bc8d/gen/builders/state_zero.go#L73-L74

Would you recommend to remove it?

**Comment by anorth** [comment]
Yes, absolutely. The `reward.ConstructState` method will populate that field with the right value.
