### ISSUE TITLE
Group related tests into one file by making json an array of vectors

### ISSUE THREAD

**Issue by austinabell** [filecoin-project/test-vectors#74]
As test vectors begin to grow, would be nice to group tests in a single file instead of having a new file for every new test and grouping based on the prefix. 

This will also help reduce file bloat especially if fuzz testing is added later. This will require the test runners to be updated to deserialize a slice/vector of the test vector struct, but is a change more easily made earlier than later.

Nothing necessary to change, just opening issue for discussion as this seemed odd to me.

thanks :)

**Comment by raulk** [comment]
@austinabell I see where you're coming from, but doing this would actually make corpus evolution and change tracing (e.g. git blame / git log) pretty painful.

We'd also need to define an explicit canonical ordering, so if a vector is modified, we surgically replace that vector in its file.

Resulting files could end up being pretty large, and it also has a deserialisation disadvantage. Imagine you only want to execute one test vector, out of a file with 100 vectors. You'd need to deserialise all vector IDs to locate the one of interest (using deferred deserialisation for other fields), to then load the vector once you've located it.

It also makes human browsing pretty unusable.

---

On the topic of fuzz/generative testing, I don't expect the corpus to drive any kind of generative testing. Implementations should run their fuzzers, and only capture the failing inputs/outputs as test vectors, for other implementations to verify.

**Comment by austinabell** [comment]
Yeah the idea would be that you could filter by test id instead of by file name. As I mentioned, the only disadvantage is you have a ton of extra files instead of being able to group similar tests. This isn't really a problem so if you don't like this idea I will just close :) Thanks for consideration

**Comment by raulk** [comment]
@austinabell Thanks for constructive input/discussion! We can re-evaluate this going forward if the corpus really does blow up in file volume. Maybe we could introduce "vector aggregates" to group vectors that test the same behaviour with many different parameters, but I certainly wouldn't expect this to be the default form.
