### ISSUE TITLE
Chaos actor CallerValidationBranch doesn't need to be bigint

### ISSUE THREAD

**Issue by austinabell** [filecoin-project/test-vectors#84]
Since it is just denoting an enum/ number (currently 0 to 3) it can be replaced with using [CborInt](https://github.com/whyrusleeping/cbor-gen/blob/0b9f6c5fb1636544f94f5087817df99699de49ba/utils.go#L654) to avoid the allocation. (not sure if there is a type for unsigned integer if that's what you want, I'm sure there must be)

Not a big deal if this doesn't change, we could avoid the allocation on our end if we wanted to, but just for future reference, or if someone wanted to change sooner than later.

**Comment by raulk** [comment]
I think we should tackle this one. It's low-hanging fruit and the sooner we do it the better. WDYT?
